# Generated by Django 5.1.2 on 2024-10-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=50)),
                ('Описание', models.TextField()),
                ('Статус', models.CharField(choices=[], default='not_started', max_length=50)),
                ('Приоритет', models.CharField(choices=[], default='medium', max_length=50)),
                ('Начало таска', models.DateTimeField(blank=True, null=True)),
                ('Конец таска', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
